{
  "media": {
    "input": "public/media",
    "output": "/media"
  },
  "content": [
    {
      "name": "navbar",
      "label": "Navbar",
      "type": "file",
      "path": "content/navbar.json",
      "format": "json",
      "fields": [
        {
          "name": "title",
          "label": "Site Title",
          "type": "string"
        },
        {
          "name": "logo",
          "label": "Logo",
          "type": "image"
        },
        {
          "name": "links",
          "label": "Navigation Links",
          "type": "object",
          "list": true,
          "fields": [
            {
              "name": "label",
              "label": "Label",
              "type": "string"
            },
            {
              "name": "url",
              "label": "URL",
              "type": "string"
            },
            {
              "name": "type",
              "label": "Type",
              "type": "string",
              "options": {
                "values": ["link", "button"]
              }
            }
          ]
        },
        {
          "name": "mobile_icon",
          "label": "Mobile Menu Icon",
          "type": "string",
          "default": "☰"
        },
        {
          "name": "search",
          "label": "Search Settings",
          "type": "object",
          "fields": [
            {
              "name": "enabled",
              "label": "Enable Search",
              "type": "boolean"
            },
            {
              "name": "placeholder",
              "label": "Placeholder Text",
              "type": "string"
            }
          ]
        }
      ]
    }
  ]
}