media:
  input: public/images
  output: /images

content:
  # === GLOBAL NAVBAR ===
  - name: navbar
    label: Navigation Bar
    path: lib/navbar.json
    type: file
    format: json
    fields:
      - name: layout
        label: Navbar Layout
        type: select
        options:
          values:
            - { label: "Space Between", value: "space-between" }
            - { label: "Space Around", value: "space-around" }
            - { label: "Center", value: "center" }
            - { label: "Left Aligned", value: "flex-start" }
            - { label: "Right Aligned", value: "flex-end" }
      
      - name: background_color
        label: Background Color (hex)
        type: string
        default: "#ffffff"
     
      - name: text_color
        label: Text Color (hex)
        type: string
        default: "#000000"

      # Logo Block Configuration
      - name: logo
        label: Logo Configuration
        type: block
        blockKey: type
        blocks:
          - name: image
            label: Image Logo
            fields:
              - name: image
                label: Logo Image
                type: image
              - name: width
                label: Width
                type: number
                default: 150
          - name: text
            label: Text Logo
            fields:
              - name: text
                label: Text
                type: string
                default: "My Site"

      # Menu Items Fix
      - name: menu_items
        label: Menu Items
        type: object
        list: true
        default: []      # Crucial: Fixes "Required" error
        required: false
        fields:
          - name: label
            label: Label
            type: string
          - name: link
            label: Link
            type: string

      - name: search_bar
        label: Search Bar
        type: object
        fields:
          - name: enabled
            label: Show Search Bar
            type: boolean
            default: false
          - name: placeholder
            label: Placeholder Text
            type: string
            default: "Search..."
          - name: width
            label: Search Bar Width (px)
            type: number
            default: 200

      - name: auth_buttons
        label: Login/Signup Buttons
        type: object
        fields:
          - name: enabled
            label: Show Auth Buttons
            type: boolean
            default: false
          - name: login_button
            label: Login Button
            type: object
            fields:
              - { name: text, label: Text, type: string, default: "Login" }
              - { name: link, label: Link, type: string, default: "/login" }
          - name: signup_button
            label: Signup Button
            type: object
            fields:
              - { name: text, label: Text, type: string, default: "Sign Up" }
              - { name: link, label: Link, type: string, default: "/signup" }

  # === DYNAMIC PAGES ===
  - name: pages
    label: Pages
    path: lib/pages
    type: collection
    format: json
    filename: "{fields.slug}.json" # Uses slug for the filename
    fields:
      - name: title
        label: Page Title
        type: string
        required: true
      - name: slug
        label: URL Slug
        type: string
        required: true
      
      # Flexible Sections Fix
      - name: sections
        label: Page Sections
        type: block
        list: true
        # required: false
        # default: []      # Crucial: Allows adding first item without error
        blockKey: type
        blocks:
          - name: hero
            label: Hero Section
            fields:
              - name: layout
                label: Layout
                type: select
                options:
                  values:
                    - { label: Standard, value: standard }
                    - { label: Reversed, value: reversed }
                    - { label: Centered, value: centered }
              - name: heading
                label: Heading Text
                type: string
              - name: heading_tag
                label: Heading Level
                type: select
                default: h1
                options:
                  values:
                    - { label: H1, value: h1 }
                    - { label: H2, value: h2 }
                    - { label: H3, value: h3 }
              - name: description
                label: Description
                type: text
              - name: image
                label: Image
                type: image
              - name: background_color
                label: Background Color (hex)
                type: string
              - name: text_color
                label: Text Color (hex)
                type: string
              - name: button_text
                label: Button Text
                type: string
              - name: button_link
                label: Button Link
                type: string

  # === FOOTER ===
  - name: footer
    label: Footer
    path: lib/data/footer.json
    type: file
    format: json
    fields:
      - name: text
        label: Footer Text
        type: string
        default: "© 2026 Your Brand"